version: '3'
services:
    node:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: csantos/backend_financeiro-img
        container_name: csantos.backendFinanceiro-ctn
        # environment:
        #     MYSQL_ROOT_PASSWORD: senha
        restart: always   
        volumes:
            - .:/usr/src/app
        ports:
            - "8080:8080"
  